export const USERS_SERVICE = Symbol('USERS_SERVICE');
export const RESTAURANTS_SERVICE = Symbol('RESTAURANTS_SERVICE');
export const MENU_SERVICE = Symbol('MENU_SERVICE');
export const FLOOR_PLANS_SERVICE = Symbol('FLOOR_PLANS_SERVICE');
export const BOOKING_SETTINGS_SERVICE = Symbol('BOOKING_SETTINGS_SERVICE');
export const REGISTRATION_NOTIFICATION_PUBLISHER = Symbol(
  'REGISTRATION_NOTIFICATION_PUBLISHER',
);
